### ISSUE TITLE
Error message filter doesn't work?

### ISSUE THREAD

**Issue by thomasfw** [mikejolley/sidebar-login#50]
I'm trying to change the error messages using the 'sidebar_login_error' filter discussed [here](https://wordpress.org/support/topic/plugin-sidebar-login-make-error-messages-customizable). I can see the filter is being used for $sidebar_login_params but is having no effect for me?

Also, unrelated but is it possible to remove the '→' character in the login button in a future release, it seems a bit unnecessary.

Cheers

**Comment by mikejolley** [comment]
sidebar_login_error is just a classname, its not to change messages. 

And you can remove the -> with a translation file or https://wordpress.org/plugins/say-what/
